[package]
name = "sortable"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["derive"]
derive = ["dep:sortable-derive"]

[dependencies]
sortable-derive = { path = "../sortable-derive", version = "0.1.0", optional = true }

[[example]]
name = "derive_table"
required-features = ["derive"]

[[example]]
name = "projection"
required-features = ["derive"]

[[example]]
name = "sort"
required-features = ["derive"]
